server {
    # Listen on port 80 (the default port for web traffic)
    listen 80;
    server_name localhost;

    # Where the compiled React static files live inside the container
    root /usr/share/nginx/html;
    index index.html;

    location / {
      
        # If it doesn't exist on the hard drive, fall back and serve /index.html
        try_files $uri $uri/ /index.html;
    }

   
}